# Documentation: http://docs.travis-ci.com/user/languages/julia/
sudo: true
language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
notifications:
  email: 
  - paulinahyzy@gmail.com
script: ./scripts/ci.sh
